### PR TITLE
Validation improvements

### LINKED ISSUE #97: (MV) Improve version directory error in storage_object_validator_spec.rb
Line 104: Clarify error code to be something like.... "Items in version directory are not correct.
Error is from version directory having files in it instead of directories

### LINKED ISSUE #103: (MV) NO_FILES_IN_MANIFEST_DIR may be thrown incorrectly
It's possible this error, detected in #check_required_manifest_files,  may be thrown when there are files in the manifest directory, but neither signatureCatalog.xml nor manifestInventory.xml is thrown.

### PR DESCRIPTION
**Pull request by ndushay**
StorageObjectValidator improvements:

- distinguish between no files in manifests/ and no required files in manifests/  (#103)
- better version sub-dir error messages (#97)
- actually use an unused error code:  FILES_IN_VERSION_DIR
- error messages to have more specific information
- add test for manifests dir having a sub-dir

Refactoring:

- rename to singular: private method  `check_correctly_formed_moab`
- use File.join to avoid machine specific File.separator char

Closes #97 
Closes #103

### CODE REVIEW

File: lib/moab/storage_object_validator.rb [hunk 1]
```diff
@@ -208,23 +222,22 @@ def error_code_msg(response_code, addl=nil)
...
-                 nil
-               elsif has_manifest_inventory && !has_signature_catalog
-                 result_hash(NO_SIGNATURE_CATALOG, version)
-               elsif !has_manifest_inventory && has_signature_catalog
-                 result_hash(NO_MANIFEST_INVENTORY, version)
-               else
-                 result_hash(NO_FILES_IN_MANIFEST_DIR, version)
-               end
-      errors << result if result
+      unless contains_file?(File.join(dir, MANIFESTS_DIR))
```
Comment (SaravShah) [inline lib/moab/storage_object_validator.rb]: does File.join provide an efficiency boost or is it easier to read? vs concatenation?

File: lib/moab/storage_object_validator.rb [hunk 2]
```diff
@@ -192,12 +190,28 @@ def missing_dir(array, version, required_sub_dirs)
...
 
+    def contains_sub_dir?(path)
+      directory_entries(path).detect { |entry| File.directory?(File.join(path, entry)) }
+    end
+
+    def contains_file?(path)
+      directory_entries(path).detect { |entry| File.file?(File.join(path, entry)) }
+    end
+
+    def basename(path)
```
Comment (SaravShah) [inline lib/moab/storage_object_validator.rb]: 👍
